Alleyhoop_VerboseMode: "log"

AlleyHoop_Sensors: {
    UltrasonicSensor_TopicName: "/arduino_slave/ultrasonic_sensor",
    ImuSensor_TopicName: "/arduino_slave/imu_sensor",
    MonoCameraImageRaw_TopicName: "/raspi_camera/image_raw",
    MonoCameraInfo_TopicName: "/raspi_camera/camera_info",
    DepthCameraImageRaw_TopicName: "/depth_camera/image_raw",
    DepthCameraInfo_TopicName: "/depth_camera/camera_info",
    DepthCameraPcl_TopicName: "/depth_camera/points",
    Lidar_TopicName: "/scan",
}

AlleyHoop_Actuators: {
    Led1_TopicName: "/arduino_slave/led1_actuator",
    SteeringMotor_TopicName: "/arduino_slave/servo",
    VelocityMotor_TopicName: "/arduino_slave/esc",
}

AlleyHoop_Models: {
  FindFeaturesOnImage_ServiceName: "example_feature_finder",
}