Alleyhoop_VerboseMode: "log"

AlleyHoop_Sensors: {
    UltrasonicSensor_TopicName: "/arduino_sensor_slave/ultrasonic_sensor",
    ImuSensor_TopicName: "/arduino_sensor_slave/imu_sensor",
    MonoCameraImageRaw_TopicName: "/camera/color/image_raw",
    MonoCameraInfo_TopicName: "/camera/color/camera_info",
    DepthCameraInfo_TopicName: "/camera/depth/camera_info",
    DepthCameraPcl_TopicName: "/camera/depth/color/points",
    Lidar_TopicName: "/scan",
}

AlleyHoop_Actuators: {
    Led1_TopicName: "/arduino_actuator_slave/led13",
    Led2_TopicName: "/arduino_sensor_slave/led13",
    SteeringMotor_TopicName: "/arduino_actuator_slave/servo",
    VelocityMotor_TopicName: "/arduino_actuator_slave/esc",
}

AlleyHoop_Models: {
  TrafficRulesFeaturesOnImage_ServiceName: "traffic_rules_feature_finder",
  ObjectFeaturesOnImage_ServiceName: "object_feature_finder",
  RoadFeaturesOnImage_ServiceName: "road_feature_finder",
}